/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightschedulerceg5409;
import java.util.List;
import javax.swing.JFrame;
/**
 *
 * @author Chloe
 */
public class MainJFrame extends javax.swing.JFrame {

    private QueryHandler queryHandler;
    private List<Day> Dates;
    private List<Flight> Flights;
    private List<Waitlist> Waiting;
    private int dateEntries = 0, flightEntries = 0, bookingEntries = 0, waitingEntries = 0;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        queryHandler = new QueryHandler();
        initComponents();
        loadDates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        bookTab = new javax.swing.JPanel();
        bookDateLabel = new javax.swing.JLabel();
        bookFlightLabel = new javax.swing.JLabel();
        bookNameLabel = new javax.swing.JLabel();
        bookFlightCBox = new javax.swing.JComboBox<>();
        bookNameText = new javax.swing.JTextField();
        bookButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookOutput = new javax.swing.JTextArea();
        bookDateCBox = new javax.swing.JComboBox<>();
        statusTab = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusOutput = new javax.swing.JTextArea();
        statusCheckLabel1 = new javax.swing.JLabel();
        statusCheckLabel2 = new javax.swing.JLabel();
        statusCheckLabel3 = new javax.swing.JLabel();
        statusDateLabel = new javax.swing.JLabel();
        statusFlightLabel = new javax.swing.JLabel();
        statusFlightButton = new javax.swing.JButton();
        statusDateCBox = new javax.swing.JComboBox<>();
        statusFlightCBox = new javax.swing.JComboBox<>();
        statusDateLabel2 = new javax.swing.JLabel();
        statusDateCBox2 = new javax.swing.JComboBox<>();
        statusWaitButton = new javax.swing.JButton();
        statusCustomerLabel = new javax.swing.JLabel();
        statusCustomerCBox = new javax.swing.JComboBox<>();
        statusCustomerButton = new javax.swing.JButton();
        cancelTab = new javax.swing.JPanel();
        cancelDateLabel = new javax.swing.JLabel();
        cancelDateCBox = new javax.swing.JComboBox<>();
        cancelCustomerLabel = new javax.swing.JLabel();
        cancelCustomerCBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cancelOutput = new javax.swing.JTextArea();
        addTab = new javax.swing.JPanel();
        addDateLabel = new javax.swing.JLabel();
        addDayText = new javax.swing.JTextField();
        addFlightLabel = new javax.swing.JLabel();
        addFlightText = new javax.swing.JTextField();
        addSeatsText = new javax.swing.JTextField();
        addDayButton = new javax.swing.JButton();
        addFlightButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        addOutput = new javax.swing.JTextArea();
        dropTab = new javax.swing.JPanel();
        dropLabel = new javax.swing.JLabel();
        dropCBox = new javax.swing.JComboBox<>();
        dropButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        dropOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");

        bookDateLabel.setText("Select a Date:");

        bookFlightLabel.setText("Select a Flight:");

        bookNameLabel.setText("Enter your Name:");

        bookButton.setText("Book This Flight");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        bookOutput.setColumns(20);
        bookOutput.setRows(5);
        jScrollPane1.setViewportView(bookOutput);

        javax.swing.GroupLayout bookTabLayout = new javax.swing.GroupLayout(bookTab);
        bookTab.setLayout(bookTabLayout);
        bookTabLayout.setHorizontalGroup(
            bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(bookTabLayout.createSequentialGroup()
                        .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bookTabLayout.createSequentialGroup()
                                .addComponent(bookNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(bookNameText))
                            .addGroup(bookTabLayout.createSequentialGroup()
                                .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookFlightLabel)
                                    .addComponent(bookDateLabel))
                                .addGap(32, 32, 32)
                                .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bookFlightCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bookDateCBox, 0, 104, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(bookButton, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bookTabLayout.setVerticalGroup(
            bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bookButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bookTabLayout.createSequentialGroup()
                        .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookDateLabel)
                            .addComponent(bookDateCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookFlightLabel)
                            .addComponent(bookFlightCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookNameLabel)
                            .addComponent(bookNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Book a Flight", bookTab);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(55, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(55, 10));

        statusOutput.setColumns(20);
        statusOutput.setRows(5);
        jScrollPane2.setViewportView(statusOutput);

        statusCheckLabel1.setText("Flight Status:");

        statusCheckLabel2.setText("Waitlist Status:");

        statusCheckLabel3.setText("Customer Status:");

        statusDateLabel.setText("Date:");

        statusFlightLabel.setText("Flight:");

        statusFlightButton.setText("Check Flight Status");
        statusFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFlightButtonActionPerformed(evt);
            }
        });

        statusDateLabel2.setText("Date:");

        statusWaitButton.setText("Check Waitlist Status");
        statusWaitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusWaitButtonActionPerformed(evt);
            }
        });

        statusCustomerLabel.setText("Name:");

        statusCustomerButton.setText("Check Customer Status");
        statusCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusTabLayout = new javax.swing.GroupLayout(statusTab);
        statusTab.setLayout(statusTabLayout);
        statusTabLayout.setHorizontalGroup(
            statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusTabLayout.createSequentialGroup()
                        .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusCheckLabel1)
                            .addGroup(statusTabLayout.createSequentialGroup()
                                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(statusDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(statusFlightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusDateCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(statusFlightCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(statusFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusWaitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(statusTabLayout.createSequentialGroup()
                                .addComponent(statusCheckLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(statusTabLayout.createSequentialGroup()
                                .addComponent(statusDateLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(statusDateCBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusCustomerButton)
                            .addComponent(statusCheckLabel3)
                            .addGroup(statusTabLayout.createSequentialGroup()
                                .addComponent(statusCustomerLabel)
                                .addGap(18, 18, 18)
                                .addComponent(statusCustomerCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        statusTabLayout.setVerticalGroup(
            statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusTabLayout.createSequentialGroup()
                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusTabLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(statusTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusCheckLabel2)
                            .addComponent(statusCheckLabel1)
                            .addComponent(statusCheckLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(statusTabLayout.createSequentialGroup()
                                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(statusDateLabel)
                                    .addComponent(statusDateCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(statusFlightLabel)
                                    .addComponent(statusFlightCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(statusTabLayout.createSequentialGroup()
                                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(statusDateLabel2)
                                    .addComponent(statusDateCBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusWaitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(statusTabLayout.createSequentialGroup()
                                .addGroup(statusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(statusCustomerLabel)
                                    .addComponent(statusCustomerCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Check Status", statusTab);

        cancelDateLabel.setText("Select a Date:");

        cancelCustomerLabel.setText("Select a Name:");

        cancelButton.setText("Cancel Flight");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        cancelOutput.setColumns(20);
        cancelOutput.setRows(5);
        jScrollPane3.setViewportView(cancelOutput);

        javax.swing.GroupLayout cancelTabLayout = new javax.swing.GroupLayout(cancelTab);
        cancelTab.setLayout(cancelTabLayout);
        cancelTabLayout.setHorizontalGroup(
            cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelTabLayout.createSequentialGroup()
                        .addGroup(cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelTabLayout.createSequentialGroup()
                                .addComponent(cancelDateLabel)
                                .addGap(18, 18, 18))
                            .addGroup(cancelTabLayout.createSequentialGroup()
                                .addComponent(cancelCustomerLabel)
                                .addGap(14, 14, 14)))
                        .addGroup(cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cancelCustomerCBox, 0, 88, Short.MAX_VALUE)
                            .addComponent(cancelDateCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        cancelTabLayout.setVerticalGroup(
            cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelTabLayout.createSequentialGroup()
                        .addGroup(cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelDateLabel)
                            .addComponent(cancelDateCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cancelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelCustomerLabel)
                            .addComponent(cancelCustomerCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cancellations", cancelTab);

        addDateLabel.setText("Add New Day:");

        addFlightLabel.setText("Add New Flight:");

        addFlightText.setText("Flight Name");

        addSeatsText.setText("Number of Seats");

        addDayButton.setText("Add Day");
        addDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayButtonActionPerformed(evt);
            }
        });

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        addOutput.setColumns(20);
        addOutput.setRows(5);
        jScrollPane4.setViewportView(addOutput);

        javax.swing.GroupLayout addTabLayout = new javax.swing.GroupLayout(addTab);
        addTab.setLayout(addTabLayout);
        addTabLayout.setHorizontalGroup(
            addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDateLabel)
                            .addComponent(addDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSeatsText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFlightText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFlightLabel))
                        .addGap(18, 18, 18)
                        .addComponent(addFlightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        addTabLayout.setVerticalGroup(
            addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addTabLayout.createSequentialGroup()
                                .addComponent(addDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addDayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTabLayout.createSequentialGroup()
                                .addComponent(addFlightLabel)
                                .addGap(18, 18, 18)
                                .addComponent(addFlightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addSeatsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addFlightButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Flight Data", addTab);

        dropLabel.setText("Choose a Flight:");

        dropButton.setText("Drop Flight");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        dropOutput.setColumns(20);
        dropOutput.setRows(5);
        jScrollPane5.setViewportView(dropOutput);

        javax.swing.GroupLayout dropTabLayout = new javax.swing.GroupLayout(dropTab);
        dropTab.setLayout(dropTabLayout);
        dropTabLayout.setHorizontalGroup(
            dropTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dropTabLayout.createSequentialGroup()
                        .addComponent(dropLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dropCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        dropTabLayout.setVerticalGroup(
            dropTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropTabLayout.createSequentialGroup()
                        .addGroup(dropTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dropLabel)
                            .addComponent(dropCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dropButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Drop Flight", dropTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookButtonActionPerformed

    private void statusFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFlightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFlightButtonActionPerformed

    private void statusWaitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusWaitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusWaitButtonActionPerformed

    private void statusCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCustomerButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayButtonActionPerformed
        int result = queryHandler.addNewDate(addDayText.getText());
        
        if (result == 1) {
            bookDateCBox.addItem(addDayText.getText());
            statusDateCBox.addItem(addDayText.getText());
            statusDateCBox2.addItem(addDayText.getText());
            cancelDateCBox.addItem(addDayText.getText());
            addOutput.setText(addOutput.getText() + "Date has been added successfully\n");
        }
        else {
            addOutput.setText(addOutput.getText() + "Error! Date has not been added\n");
        }
    }//GEN-LAST:event_addDayButtonActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropButtonActionPerformed

    private void loadDates() {
        try {
            Dates = queryHandler.getAllDates();
            dateEntries = Dates.size();
            
            for (int i = 0; i < dateEntries; i++) {
                bookDateCBox.addItem(Dates.get(i).getFlightDate());
                statusDateCBox.addItem(Dates.get(i).getFlightDate());
                statusDateCBox2.addItem(Dates.get(i).getFlightDate());
                cancelDateCBox.addItem(Dates.get(i).getFlightDate());
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        MainJFrame mainJFrame = new MainJFrame();
        mainJFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainJFrame.setSize(550,400);
        mainJFrame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDateLabel;
    private javax.swing.JButton addDayButton;
    private javax.swing.JTextField addDayText;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JLabel addFlightLabel;
    private javax.swing.JTextField addFlightText;
    private javax.swing.JTextArea addOutput;
    private javax.swing.JTextField addSeatsText;
    private javax.swing.JPanel addTab;
    private javax.swing.JButton bookButton;
    private javax.swing.JComboBox<String> bookDateCBox;
    private javax.swing.JLabel bookDateLabel;
    private javax.swing.JComboBox<String> bookFlightCBox;
    private javax.swing.JLabel bookFlightLabel;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameText;
    private javax.swing.JTextArea bookOutput;
    private javax.swing.JPanel bookTab;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cancelCustomerCBox;
    private javax.swing.JLabel cancelCustomerLabel;
    private javax.swing.JComboBox<String> cancelDateCBox;
    private javax.swing.JLabel cancelDateLabel;
    private javax.swing.JTextArea cancelOutput;
    private javax.swing.JPanel cancelTab;
    private javax.swing.JButton dropButton;
    private javax.swing.JComboBox<String> dropCBox;
    private javax.swing.JLabel dropLabel;
    private javax.swing.JTextArea dropOutput;
    private javax.swing.JPanel dropTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel statusCheckLabel1;
    private javax.swing.JLabel statusCheckLabel2;
    private javax.swing.JLabel statusCheckLabel3;
    private javax.swing.JButton statusCustomerButton;
    private javax.swing.JComboBox<String> statusCustomerCBox;
    private javax.swing.JLabel statusCustomerLabel;
    private javax.swing.JComboBox<String> statusDateCBox;
    private javax.swing.JComboBox<String> statusDateCBox2;
    private javax.swing.JLabel statusDateLabel;
    private javax.swing.JLabel statusDateLabel2;
    private javax.swing.JButton statusFlightButton;
    private javax.swing.JComboBox<String> statusFlightCBox;
    private javax.swing.JLabel statusFlightLabel;
    private javax.swing.JTextArea statusOutput;
    private javax.swing.JPanel statusTab;
    private javax.swing.JButton statusWaitButton;
    // End of variables declaration//GEN-END:variables
}
